# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/yoni/dev_stu/cpp/pilo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/yoni/dev_stu/cpp/pilo

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/yoni/dev_stu/cpp/pilo/CMakeFiles /Users/yoni/dev_stu/cpp/pilo/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/yoni/dev_stu/cpp/pilo/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pilo

# Build rule for target.
pilo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pilo
.PHONY : pilo

# fast build rule for target.
pilo/fast:
	$(MAKE) -f CMakeFiles/pilo.dir/build.make CMakeFiles/pilo.dir/build
.PHONY : pilo/fast

#=============================================================================
# Target rules for targets named cpr

# Build rule for target.
cpr: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cpr
.PHONY : cpr

# fast build rule for target.
cpr/fast:
	$(MAKE) -f include/libcurlCPR/cpr/cpr/CMakeFiles/cpr.dir/build.make include/libcurlCPR/cpr/cpr/CMakeFiles/cpr.dir/build
.PHONY : cpr/fast

DELL.o: DELL.cpp.o

.PHONY : DELL.o

# target to build an object file
DELL.cpp.o:
	$(MAKE) -f CMakeFiles/pilo.dir/build.make CMakeFiles/pilo.dir/DELL.cpp.o
.PHONY : DELL.cpp.o

DELL.i: DELL.cpp.i

.PHONY : DELL.i

# target to preprocess a source file
DELL.cpp.i:
	$(MAKE) -f CMakeFiles/pilo.dir/build.make CMakeFiles/pilo.dir/DELL.cpp.i
.PHONY : DELL.cpp.i

DELL.s: DELL.cpp.s

.PHONY : DELL.s

# target to generate assembly for a file
DELL.cpp.s:
	$(MAKE) -f CMakeFiles/pilo.dir/build.make CMakeFiles/pilo.dir/DELL.cpp.s
.PHONY : DELL.cpp.s

HP.o: HP.cpp.o

.PHONY : HP.o

# target to build an object file
HP.cpp.o:
	$(MAKE) -f CMakeFiles/pilo.dir/build.make CMakeFiles/pilo.dir/HP.cpp.o
.PHONY : HP.cpp.o

HP.i: HP.cpp.i

.PHONY : HP.i

# target to preprocess a source file
HP.cpp.i:
	$(MAKE) -f CMakeFiles/pilo.dir/build.make CMakeFiles/pilo.dir/HP.cpp.i
.PHONY : HP.cpp.i

HP.s: HP.cpp.s

.PHONY : HP.s

# target to generate assembly for a file
HP.cpp.s:
	$(MAKE) -f CMakeFiles/pilo.dir/build.make CMakeFiles/pilo.dir/HP.cpp.s
.PHONY : HP.cpp.s

ILO.o: ILO.cpp.o

.PHONY : ILO.o

# target to build an object file
ILO.cpp.o:
	$(MAKE) -f CMakeFiles/pilo.dir/build.make CMakeFiles/pilo.dir/ILO.cpp.o
.PHONY : ILO.cpp.o

ILO.i: ILO.cpp.i

.PHONY : ILO.i

# target to preprocess a source file
ILO.cpp.i:
	$(MAKE) -f CMakeFiles/pilo.dir/build.make CMakeFiles/pilo.dir/ILO.cpp.i
.PHONY : ILO.cpp.i

ILO.s: ILO.cpp.s

.PHONY : ILO.s

# target to generate assembly for a file
ILO.cpp.s:
	$(MAKE) -f CMakeFiles/pilo.dir/build.make CMakeFiles/pilo.dir/ILO.cpp.s
.PHONY : ILO.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/pilo.dir/build.make CMakeFiles/pilo.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/pilo.dir/build.make CMakeFiles/pilo.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/pilo.dir/build.make CMakeFiles/pilo.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... pilo"
	@echo "... cpr"
	@echo "... DELL.o"
	@echo "... DELL.i"
	@echo "... DELL.s"
	@echo "... HP.o"
	@echo "... HP.i"
	@echo "... HP.s"
	@echo "... ILO.o"
	@echo "... ILO.i"
	@echo "... ILO.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

